name: Build docs and release to GitHub Pages from master
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Install Doxygen and Graphviz
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen graphviz
          version: 1.0  # Version of cache to load. Each version will have its own cache.

      - name: Build docs
        uses: threeal/cmake-action@v2.0.0
        with:
          source-dir: ./
          build-dir: build
          options: |
            LT_BUILD_DOCS=ON
            LT_USE_TREZOR_CRYPTO=ON

      - name: Upload built html as artifact
        id: html_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/doxygen/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.html_artifact.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: pages_deployment
        uses: actions/deploy-pages@v4
