name: Run static code analysis
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  static_analysis:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
            sudo apt-get install cmake build-essential cppcheck

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      
      - name: Run CodeChecker analysis
        uses: tropicsquare/github-actions/CodeChecker-Action-1.0.4@main
        id: codechecker
        with:
          config: ./scripts/codechecker/codechecker_config.json
          build-command: ./scripts/codechecker/codechecker_build.sh

      - name: Upload results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}

      # For now let's keep this disabled.
      # - name: "Break build if CodeChecker reported any findings"
      #   if: ${{ steps.codechecker.outputs.warnings == 'true' }}
      #   run: exit 1