name: Unit tests and coverage
on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set Ceedling config path
        run: echo "CEEDLING_MAIN_PROJECT_FILE=scripts/ceedling.yml" >>$GITHUB_ENV

      - name: Run Ceedling Unit Tests
        uses: pavelpolach321/action-ceedling-unit-test@2.0.0
        with:
          unit-test-path: '${{ github.workspace }}/'
